image: dealii/dealii:master-focal

before_script:
  - export D=/builds/luca-heltai/bare-dealii-app
  - cd $D
  - ./scripts/check_indentation.sh

debug:
  script:
   - export D=/builds/luca-heltai/bare-dealii-app
   - cd $D
   - test -d build_linux_debug && rm -rf build_linux_debug
   - mkdir build_linux_debug; cd build_linux_debug; cmake .. -GNinja -DCMAKE_BUILD_TYPE=Debug; ninja
   - ctest -N; ctest --output-on-failure

release:
  script:
   - export D=/builds/luca-heltai/bare-dealii-app
   - cd $D
   - test -d build_linux_release && rm -rf build_linux_release
   - mkdir build_linux_release; cd build_linux_release; cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release; ninja
   - ctest -N; ctest --output-on-failure
