sudo: required

env:
  - BUILD_TYPE=Release
  - BUILD_TYPE=Debug

services:
  - docker

notifications:
  email: false

language: C++

before_install:
- ./scripts/dr.sh "./scripts/check_indentation.sh"

script:
- ./scripts/dr.sh "test -d ./build-travis-${BUILD_TYPE} && rm -rf ./build-travis-${BUILD_TYPE}; mkdir ./build-travis-${BUILD_TYPE}; cd ./build-travis-${BUILD_TYPE}; cmake -GNinja -DCMAKE_BUILD_TYPE=$BUILD_TYPE ../; ninja"
- ./scripts/dr.sh "cd ./build-travis-${BUILD_TYPE}; ctest -N; ctest --output-on-failure"
