sudo: required

env:
  - BUILD_TYPE=Release
  - BUILD_TYPE=Debug

services:
  - docker

notifications:
  email: false

language: C++

before_install:
- export IMG=mathlab/deal2lkit:dev-debugrelease 
- alias dr="docker run -P -v `pwd`:/home/dealii/app:rw $IMG /bin/sh -c"
- docker pull $IMG
- dr "cd app; ./scripts/check_indentation.sh"

script:
- dr "mkdir app/build; cd app/build; cmake -GNinja ../; ninja"
- dr "cd app/build; ctest -N; ctest -V"
