Template Deal.II Application: Laplacian< dim > Class Template Reference
Laplacian< dim > Class Template Reference
#include <laplacian.h>
Public Member Functions
Laplacian ()
void run ()
Private Member Functions
void setup_system ()
void assemble_system ()
void solve ()
void refine_grid ()
void output_results (const unsigned int cycle) const
Private Attributes
Triangulation< dim > triangulation
FE_Q< dim > fe
DoFHandler< dim > dof_handler
AffineConstraints< double > constraints
SparseMatrix< double > system_matrix
SparsityPattern sparsity_pattern
Vector< double > solution
Vector< double > system_rhs
Detailed Description
template<int dim>
class Laplacian< dim >
Definition at line 39 of file laplacian.h.
Constructor & Destructor Documentation
Laplacian()
template<int dim> Laplacian< dim >::Laplacian ()
Definition at line 67 of file laplacian.cc.
References triangulation.
Member Function Documentation
assemble_system()
template<int dim> void Laplacian< dim >::assemble_system () private
Definition at line 109 of file laplacian.cc.
References coefficient(), FEValues< int dim, int spacedim >::dof_indices(), FEValues< int dim, int spacedim >::JxW(), FEValues< int dim, int spacedim >::quadrature_point(), FEValues< int dim, int spacedim >::quadrature_point_indices(), FEValues< int dim, int spacedim >::reinit(), FEValues< int dim, int spacedim >::shape_grad(), FEValues< int dim, int spacedim >::shape_value(), update_gradients, update_JxW_values, update_quadrature_points, and update_values.
output_results()
template<int dim> void Laplacian< dim >::output_results (const unsigned int cycle) const private
Definition at line 200 of file laplacian.cc.
References DataOut< int dim, int spacedim >::add_data_vector(), DataOut< int dim, int spacedim >::attach_dof_handler(), DataOut< int dim, int spacedim >::build_patches(), GridOut::set_flags(), triangulation, GridOut::write_gnuplot(), and DataOut< int dim, int spacedim >::write_vtu().
refine_grid()
template<int dim> void Laplacian< dim >::refine_grid () private
Definition at line 178 of file laplacian.cc.
References KellyErrorEstimator< int dim, int spacedim >::estimate(), GridRefinement::refine_and_coarsen_fixed_number(), and triangulation.
run()
template<int dim> void Laplacian< dim >::run ()
Definition at line 226 of file laplacian.cc.
References GridGenerator::hyper_ball(), and triangulation.
Referenced by main().
setup_system()
template<int dim> void Laplacian< dim >::setup_system () private
Definition at line 76 of file laplacian.cc.
References VectorTools::interpolate_boundary_values(), DoFTools::make_hanging_node_constraints(), and DoFTools::make_sparsity_pattern().
solve()
template<int dim> void Laplacian< dim >::solve () private
Definition at line 161 of file laplacian.cc.
References e(), PreconditionSSOR< typename MatrixType >::initialize(), and SolverCG< typename VectorType >::solve().
Member Data Documentation
constraints
template<int dim> AffineConstraints<double> Laplacian< dim >::constraints private
Definition at line 65 of file laplacian.h.
dof_handler
template<int dim> DoFHandler<dim> Laplacian< dim >::dof_handler private
Definition at line 62 of file laplacian.h.
fe
template<int dim> FE_Q<dim> Laplacian< dim >::fe private
Definition at line 61 of file laplacian.h.
solution
template<int dim> Vector<double> Laplacian< dim >::solution private
Definition at line 70 of file laplacian.h.
sparsity_pattern
template<int dim> SparsityPattern Laplacian< dim >::sparsity_pattern private
Definition at line 68 of file laplacian.h.
system_matrix
template<int dim> SparseMatrix<double> Laplacian< dim >::system_matrix private
Definition at line 67 of file laplacian.h.
system_rhs
template<int dim> Vector<double> Laplacian< dim >::system_rhs private
Definition at line 71 of file laplacian.h.
triangulation
template<int dim> Triangulation<dim> Laplacian< dim >::triangulation private
Definition at line 59 of file laplacian.h.
The documentation for this class was generated from the following files:
/github/workspace/include/laplacian.h
/github/workspace/source/laplacian.cc