# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /workspaces/bare-dealii-app

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /workspaces/bare-dealii-app

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /workspaces/bare-dealii-app/CMakeFiles /workspaces/bare-dealii-app/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /workspaces/bare-dealii-app/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named indent

# Build rule for target.
indent: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 indent
.PHONY : indent

# fast build rule for target.
indent/fast:
	$(MAKE) -f CMakeFiles/indent.dir/build.make CMakeFiles/indent.dir/build
.PHONY : indent/fast

#=============================================================================
# Target rules for targets named laplacian_3d.g

# Build rule for target.
laplacian_3d.g: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 laplacian_3d.g
.PHONY : laplacian_3d.g

# fast build rule for target.
laplacian_3d.g/fast:
	$(MAKE) -f CMakeFiles/laplacian_3d.g.dir/build.make CMakeFiles/laplacian_3d.g.dir/build
.PHONY : laplacian_3d.g/fast

#=============================================================================
# Target rules for targets named laplacian_1d.g

# Build rule for target.
laplacian_1d.g: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 laplacian_1d.g
.PHONY : laplacian_1d.g

# fast build rule for target.
laplacian_1d.g/fast:
	$(MAKE) -f CMakeFiles/laplacian_1d.g.dir/build.make CMakeFiles/laplacian_1d.g.dir/build
.PHONY : laplacian_1d.g/fast

#=============================================================================
# Target rules for targets named laplacian_2d.g

# Build rule for target.
laplacian_2d.g: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 laplacian_2d.g
.PHONY : laplacian_2d.g

# fast build rule for target.
laplacian_2d.g/fast:
	$(MAKE) -f CMakeFiles/laplacian_2d.g.dir/build.make CMakeFiles/laplacian_2d.g.dir/build
.PHONY : laplacian_2d.g/fast

#=============================================================================
# Target rules for targets named laplacian-lib.g

# Build rule for target.
laplacian-lib.g: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 laplacian-lib.g
.PHONY : laplacian-lib.g

# fast build rule for target.
laplacian-lib.g/fast:
	$(MAKE) -f CMakeFiles/laplacian-lib.g.dir/build.make CMakeFiles/laplacian-lib.g.dir/build
.PHONY : laplacian-lib.g/fast

#=============================================================================
# Target rules for targets named template.debug.diff

# Build rule for target.
template.debug.diff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 template.debug.diff
.PHONY : template.debug.diff

# fast build rule for target.
template.debug.diff/fast:
	$(MAKE) -f tests/CMakeFiles/template.debug.diff.dir/build.make tests/CMakeFiles/template.debug.diff.dir/build
.PHONY : template.debug.diff/fast

#=============================================================================
# Target rules for targets named template.debug

# Build rule for target.
template.debug: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 template.debug
.PHONY : template.debug

# fast build rule for target.
template.debug/fast:
	$(MAKE) -f tests/CMakeFiles/template.debug.dir/build.make tests/CMakeFiles/template.debug.dir/build
.PHONY : template.debug/fast

source/laplacian.o: source/laplacian.cc.o

.PHONY : source/laplacian.o

# target to build an object file
source/laplacian.cc.o:
	$(MAKE) -f CMakeFiles/laplacian-lib.g.dir/build.make CMakeFiles/laplacian-lib.g.dir/source/laplacian.cc.o
.PHONY : source/laplacian.cc.o

source/laplacian.i: source/laplacian.cc.i

.PHONY : source/laplacian.i

# target to preprocess a source file
source/laplacian.cc.i:
	$(MAKE) -f CMakeFiles/laplacian-lib.g.dir/build.make CMakeFiles/laplacian-lib.g.dir/source/laplacian.cc.i
.PHONY : source/laplacian.cc.i

source/laplacian.s: source/laplacian.cc.s

.PHONY : source/laplacian.s

# target to generate assembly for a file
source/laplacian.cc.s:
	$(MAKE) -f CMakeFiles/laplacian-lib.g.dir/build.make CMakeFiles/laplacian-lib.g.dir/source/laplacian.cc.s
.PHONY : source/laplacian.cc.s

source/main.o: source/main.cc.o

.PHONY : source/main.o

# target to build an object file
source/main.cc.o:
	$(MAKE) -f CMakeFiles/laplacian_3d.g.dir/build.make CMakeFiles/laplacian_3d.g.dir/source/main.cc.o
	$(MAKE) -f CMakeFiles/laplacian_1d.g.dir/build.make CMakeFiles/laplacian_1d.g.dir/source/main.cc.o
	$(MAKE) -f CMakeFiles/laplacian_2d.g.dir/build.make CMakeFiles/laplacian_2d.g.dir/source/main.cc.o
.PHONY : source/main.cc.o

source/main.i: source/main.cc.i

.PHONY : source/main.i

# target to preprocess a source file
source/main.cc.i:
	$(MAKE) -f CMakeFiles/laplacian_3d.g.dir/build.make CMakeFiles/laplacian_3d.g.dir/source/main.cc.i
	$(MAKE) -f CMakeFiles/laplacian_1d.g.dir/build.make CMakeFiles/laplacian_1d.g.dir/source/main.cc.i
	$(MAKE) -f CMakeFiles/laplacian_2d.g.dir/build.make CMakeFiles/laplacian_2d.g.dir/source/main.cc.i
.PHONY : source/main.cc.i

source/main.s: source/main.cc.s

.PHONY : source/main.s

# target to generate assembly for a file
source/main.cc.s:
	$(MAKE) -f CMakeFiles/laplacian_3d.g.dir/build.make CMakeFiles/laplacian_3d.g.dir/source/main.cc.s
	$(MAKE) -f CMakeFiles/laplacian_1d.g.dir/build.make CMakeFiles/laplacian_1d.g.dir/source/main.cc.s
	$(MAKE) -f CMakeFiles/laplacian_2d.g.dir/build.make CMakeFiles/laplacian_2d.g.dir/source/main.cc.s
.PHONY : source/main.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... test"
	@echo "... indent"
	@echo "... laplacian_3d.g"
	@echo "... laplacian_1d.g"
	@echo "... laplacian_2d.g"
	@echo "... laplacian-lib.g"
	@echo "... template.debug.diff"
	@echo "... template.debug"
	@echo "... source/laplacian.o"
	@echo "... source/laplacian.i"
	@echo "... source/laplacian.s"
	@echo "... source/main.o"
	@echo "... source/main.i"
	@echo "... source/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

