var searchData=
[
  ['base_9804',['Base',['http://www.dealii.org/developer/doxygen/deal.II/classMatrixFreeOperators_1_1Base.html',1,'MatrixFreeOperators::Base&lt; dim, VectorType, VectorizedArrayType &gt;'],['http://www.dealii.org/developer/doxygen/deal.II/structReferenceCell_1_1internal_1_1Info_1_1Base.html',1,'ReferenceCell::internal::Info::Base']]],
  ['baseiterator_9805',['BaseIterator',['http://www.dealii.org/developer/doxygen/deal.II/classBaseIterator.html',1,'']]],
  ['baseqr_9806',['BaseQR',['http://www.dealii.org/developer/doxygen/deal.II/classBaseQR.html',1,'']]],
  ['batchoptimizer_9807',['BatchOptimizer',['http://www.dealii.org/developer/doxygen/deal.II/classDifferentiation_1_1SD_1_1BatchOptimizer.html',1,'Differentiation::SD']]],
  ['bessel1_9808',['Bessel1',['http://www.dealii.org/developer/doxygen/deal.II/classFunctions_1_1Bessel1.html',1,'Functions']]],
  ['binop_5faddition_9809',['Binop_Addition',['http://www.dealii.org/developer/doxygen/deal.II/structLinearAlgebra_1_1CUDAWrappers_1_1kernel_1_1Binop__Addition.html',1,'LinearAlgebra::CUDAWrappers::kernel']]],
  ['binop_5faddition_3c_20std_3a_3acomplex_3c_20number_20_3e_20_3e_9810',['Binop_Addition&lt; std::complex&lt; Number &gt; &gt;',['http://www.dealii.org/developer/doxygen/deal.II/structLinearAlgebra_1_1CUDAWrappers_1_1kernel_1_1Binop__Addition_3_01std_1_1complex_3_01Number_01_4_01_4.html',1,'LinearAlgebra::CUDAWrappers::kernel']]],
  ['binop_5fmax_9811',['Binop_Max',['http://www.dealii.org/developer/doxygen/deal.II/structLinearAlgebra_1_1CUDAWrappers_1_1kernel_1_1Binop__Max.html',1,'LinearAlgebra::CUDAWrappers::kernel']]],
  ['binop_5fmax_3c_20std_3a_3acomplex_3c_20number_20_3e_20_3e_9812',['Binop_Max&lt; std::complex&lt; Number &gt; &gt;',['http://www.dealii.org/developer/doxygen/deal.II/structLinearAlgebra_1_1CUDAWrappers_1_1kernel_1_1Binop__Max_3_01std_1_1complex_3_01Number_01_4_01_4.html',1,'LinearAlgebra::CUDAWrappers::kernel']]],
  ['binop_5fmin_9813',['Binop_Min',['http://www.dealii.org/developer/doxygen/deal.II/structLinearAlgebra_1_1CUDAWrappers_1_1kernel_1_1Binop__Min.html',1,'LinearAlgebra::CUDAWrappers::kernel']]],
  ['binop_5fmin_3c_20std_3a_3acomplex_3c_20number_20_3e_20_3e_9814',['Binop_Min&lt; std::complex&lt; Number &gt; &gt;',['http://www.dealii.org/developer/doxygen/deal.II/structLinearAlgebra_1_1CUDAWrappers_1_1kernel_1_1Binop__Min_3_01std_1_1complex_3_01Number_01_4_01_4.html',1,'LinearAlgebra::CUDAWrappers::kernel']]],
  ['binop_5fsubtraction_9815',['Binop_Subtraction',['http://www.dealii.org/developer/doxygen/deal.II/structLinearAlgebra_1_1CUDAWrappers_1_1kernel_1_1Binop__Subtraction.html',1,'LinearAlgebra::CUDAWrappers::kernel']]],
  ['binop_5fsubtraction_3c_20std_3a_3acomplex_3c_20number_20_3e_20_3e_9816',['Binop_Subtraction&lt; std::complex&lt; Number &gt; &gt;',['http://www.dealii.org/developer/doxygen/deal.II/structLinearAlgebra_1_1CUDAWrappers_1_1kernel_1_1Binop__Subtraction_3_01std_1_1complex_3_01Number_01_4_01_4.html',1,'LinearAlgebra::CUDAWrappers::kernel']]],
  ['blockdynamicsparsitypattern_9817',['BlockDynamicSparsityPattern',['http://www.dealii.org/developer/doxygen/deal.II/classBlockDynamicSparsityPattern.html',1,'']]],
  ['blockindices_9818',['BlockIndices',['http://www.dealii.org/developer/doxygen/deal.II/classBlockIndices.html',1,'']]],
  ['blockinfo_9819',['BlockInfo',['http://www.dealii.org/developer/doxygen/deal.II/classBlockInfo.html',1,'']]],
  ['blocklinearoperator_9820',['BlockLinearOperator',['http://www.dealii.org/developer/doxygen/deal.II/classBlockLinearOperator.html',1,'']]],
  ['blockmask_9821',['BlockMask',['http://www.dealii.org/developer/doxygen/deal.II/classBlockMask.html',1,'']]],
  ['blockmatrixbase_9822',['BlockMatrixBase',['http://www.dealii.org/developer/doxygen/deal.II/classBlockMatrixBase.html',1,'']]],
  ['blockmatrixbase_3c_20sparsematrix_20_3e_9823',['BlockMatrixBase&lt; SparseMatrix &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classBlockMatrixBase.html',1,'']]],
  ['blockmatrixbase_3c_20sparsematrix_3c_20number_20_3e_20_3e_9824',['BlockMatrixBase&lt; SparseMatrix&lt; number &gt; &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classBlockMatrixBase.html',1,'']]],
  ['blocksparsematrix_9825',['BlockSparseMatrix',['http://www.dealii.org/developer/doxygen/deal.II/classPETScWrappers_1_1MPI_1_1BlockSparseMatrix.html',1,'PETScWrappers::MPI::BlockSparseMatrix'],['http://www.dealii.org/developer/doxygen/deal.II/classTrilinosWrappers_1_1BlockSparseMatrix.html',1,'TrilinosWrappers::BlockSparseMatrix'],['http://www.dealii.org/developer/doxygen/deal.II/classBlockSparseMatrix.html',1,'BlockSparseMatrix&lt; number &gt;']]],
  ['blocksparsematrixez_9826',['BlockSparseMatrixEZ',['http://www.dealii.org/developer/doxygen/deal.II/classBlockSparseMatrixEZ.html',1,'']]],
  ['blocksparsitypattern_9827',['BlockSparsityPattern',['http://www.dealii.org/developer/doxygen/deal.II/classBlockSparsityPattern.html',1,'BlockSparsityPattern'],['http://www.dealii.org/developer/doxygen/deal.II/classTrilinosWrappers_1_1BlockSparsityPattern.html',1,'TrilinosWrappers::BlockSparsityPattern']]],
  ['blocksparsitypatternbase_9828',['BlockSparsityPatternBase',['http://www.dealii.org/developer/doxygen/deal.II/classBlockSparsityPatternBase.html',1,'']]],
  ['blocksparsitypatternbase_3c_20dynamicsparsitypattern_20_3e_9829',['BlockSparsityPatternBase&lt; DynamicSparsityPattern &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classBlockSparsityPatternBase.html',1,'']]],
  ['blocksparsitypatternbase_3c_20sparsitypattern_20_3e_9830',['BlockSparsityPatternBase&lt; SparsityPattern &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classBlockSparsityPatternBase.html',1,'']]],
  ['blockvector_9831',['BlockVector',['http://www.dealii.org/developer/doxygen/deal.II/classLinearAlgebra_1_1distributed_1_1BlockVector.html',1,'LinearAlgebra::distributed::BlockVector&lt; Number &gt;'],['http://www.dealii.org/developer/doxygen/deal.II/classPETScWrappers_1_1MPI_1_1BlockVector.html',1,'PETScWrappers::MPI::BlockVector'],['http://www.dealii.org/developer/doxygen/deal.II/classTrilinosWrappers_1_1MPI_1_1BlockVector.html',1,'TrilinosWrappers::MPI::BlockVector'],['http://www.dealii.org/developer/doxygen/deal.II/classBlockVector.html',1,'BlockVector&lt; Number &gt;']]],
  ['blockvector_3c_20number_20_3e_9832',['BlockVector&lt; number &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classBlockVector.html',1,'']]],
  ['blockvectorbase_9833',['BlockVectorBase',['http://www.dealii.org/developer/doxygen/deal.II/classBlockVectorBase.html',1,'']]],
  ['blockvectorbase_3c_20mpi_3a_3avector_20_3e_9834',['BlockVectorBase&lt; MPI::Vector &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classBlockVectorBase.html',1,'']]],
  ['blockvectorbase_3c_20vector_20_3e_9835',['BlockVectorBase&lt; Vector &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classBlockVectorBase.html',1,'']]],
  ['blockvectorbase_3c_20vector_3c_20number_20_3e_20_3e_9836',['BlockVectorBase&lt; Vector&lt; number &gt; &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classBlockVectorBase.html',1,'BlockVectorBase&lt; Vector&lt; number &gt; &gt;'],['http://www.dealii.org/developer/doxygen/deal.II/classBlockVectorBase.html',1,'BlockVectorBase&lt; Vector&lt; Number &gt; &gt;']]],
  ['body_9837',['Body',['http://www.dealii.org/developer/doxygen/deal.II/structparallel_1_1internal_1_1Body.html',1,'parallel::internal']]],
  ['bool_9838',['Bool',['http://www.dealii.org/developer/doxygen/deal.II/classPatterns_1_1Bool.html',1,'Patterns']]],
  ['boolstorage_9839',['BoolStorage',['http://www.dealii.org/developer/doxygen/deal.II/structinternal_1_1TemplateConstraints_1_1BoolStorage.html',1,'internal::TemplateConstraints']]],
  ['boundaryormaterialid_9840',['BoundaryOrMaterialId',['http://www.dealii.org/developer/doxygen/deal.II/structinternal_1_1TriangulationImplementation_1_1TriaObjects_1_1BoundaryOrMaterialId.html',1,'internal::TriangulationImplementation::TriaObjects']]],
  ['boundingbox_9841',['BoundingBox',['http://www.dealii.org/developer/doxygen/deal.II/classBoundingBox.html',1,'']]],
  ['boundingbox_3c_200_2c_20number_20_3e_9842',['BoundingBox&lt; 0, Number &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classBoundingBox_3_010_00_01Number_01_4.html',1,'']]],
  ['boundingbox_3c_20boost_3a_3ageometry_3a_3adimension_3c_20box_20_3e_3a_3avalue_20_3e_9843',['BoundingBox&lt; boost::geometry::dimension&lt; Box &gt;::value &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classBoundingBox.html',1,'']]],
  ['boundingboxdataout_9844',['BoundingBoxDataOut',['http://www.dealii.org/developer/doxygen/deal.II/classBoundingBoxDataOut.html',1,'']]]
];
